name: .NET Build & UnitTests

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "src/**"
  pull_request:
    paths:
    - "src/**"
  
env:
  username: ゆーざTest
  apikey: ${{ secrets.SAMPLEAPIKEY }}

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            osName: Linux
          - os: windows-latest
            osName: Windows
    name: Test on ${{ matrix.osName }}
    permissions:
      contents: read
    uses: MareMare/ReusableWorkflows/.github/workflows/ci.net6.yml@main
    with:
      runner-os: ${{ matrix.os }}
      working-directory: src
      testing-directory: src
      run-unittest: 'true'
      unittest-filter: ''
